# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop
- release/*

pr:
- master
- develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:

# Install .NET Core SDK
- task: DotNetCoreInstaller@1
  inputs:
    version: '2.2.402'
- task: DotNetCoreInstaller@1
  inputs:
    version: '3.0.100-preview9-014004'

# SonarCloud Prepare Analysis
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud Daniel127'
    organization: 'daniel127'
    scannerMode: 'MSBuild'
    projectKey: 'semanticui-razor-components'
    projectName: 'Semantic UI Razor Components'

# Build solution
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'

# SonarCloud analyze and publish results
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'